export { default as Instagram } from './Instagram'
export { default as Sun } from './Sun'
export { default as Moon } from './Moon'
export { default as GoBack } from './GoBack'
export { default as Twitter } from './Twitter'
